### ISSUE TITLE
Provide branding images for CORE-V IDE 

### ISSUE THREAD

**Issue by ruspl-afed** [openhwgroup/core-v-ide-cdt#14]
The standard set of images for Eclipse product:
* splash.bmp
* core-v_lg.png (for About)
* core-v_16.png
* core-v_32.png
* core-v_48.png
* core-v_64.png
* core-v_128.png

Would be nice to have images for launchers, but it can wait.

**Comment by zelenyhleb** [comment]
![openhwsplash](https://user-images.githubusercontent.com/15957500/90523496-a0000300-e175-11ea-9cf4-f6c1d23b5b6d.png)
![openhwabout](https://user-images.githubusercontent.com/15957500/90524943-57494980-e177-11ea-944c-df9db8a286d6.png)

Drawed a splash and about screen based on project logo. What do you think?

**Comment by zelenyhleb** [comment]
Also, does the project have any **branding** font, or I can use any free-to-use font to write copyrights on the splash?

**Comment by rickoco** [comment]
> Also, does the project have any **branding** font, or I can use any free-to-use font to write copyrights on the splash?

These look great @zelenyhleb !!  The fonts we use are Open Sans for body text and Orbitron for titles.  Attached is the OpenHW Style Guide created by @AndreaFionda and the team at Publitek, the marketing agency for OpenHW Group.
[OPENHW-styleguide_v1.pdf](https://github.com/openhwgroup/core-v-ide-cdt/files/5091923/OPENHW-styleguide_v1.pdf)

**Comment by ruspl-afed** [comment]
Thanks @zelenyhleb
